### ISSUE TITLE
@wait_for couldn't be applied above @classmethod

### ISSUE THREAD

**Issue by vak** [itamarst/crochet#55]
modified crochet's example to show the case:

``` python
#!/usr/bin/python
"""
Do a DNS lookup using Twisted's APIs.
"""
from __future__ import print_function

# The Twisted code we'll be using:
from twisted.names import client

from crochet import setup, wait_for
setup()


# Crochet layer, wrapping Twisted's DNS library in a blocking call.
class C(object):
    @wait_for(timeout=5.0)
    @classmethod
    def gethostbyname(cls, name):
        """Lookup the IP of a given hostname.

        Unlike socket.gethostbyname() which can take an arbitrary amount of time
        to finish, this function will raise crochet.TimeoutError if more than 5
        seconds elapse without an answer being received.
        """
        d = client.lookupAddress(name)
        d.addCallback(lambda result: result[0][0].payload.dottedQuad())
        return d


if __name__ == '__main__':
    # Application code using the public API - notice it works in a normal
    # blocking manner, with no event loop visible:
    import sys
    name = sys.argv[1]
    ip = C().gethostbyname(name)
    print(name, "->", ip)

```

Error on run with python 2.7:

```
Traceback (most recent call last):
  File "/tmp/test.py", line 15, in <module>
    class C(object):
  File "/tmp/test.py", line 17, in C
    @classmethod
  File "/usr/local/lib/python2.7/dist-packages/crochet-1.2.0-py2.7.egg/crochet/_eventloop.py", line 447, in decorator
    @wraps(function)
  File "/usr/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'classmethod' object has no attribute '__module__'
```

Error on run with pypy:

```
Traceback (most recent call last):
  File "app_main.py", line 72, in run_toplevel
  File "/tmp/test.py", line 15, in <module>
    class C(object):
  File "/tmp/test.py", line 17, in C
    @classmethod
  File "/usr/local/lib/pypy2.7/dist-packages/crochet/_eventloop.py", line 447, in decorator
    @wraps(function)
  File "/usr/lib/pypy/lib_pypy/_functools.py", line 22, in __call__
    return self.func(*(self.args + fargs), **fkeywords)
  File "/usr/lib/pypy/lib-python/2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'classmethod' object has no attribute '__module__'
```

**Comment by itamarst** [comment]
I believe #82 ought to fix this ... although it sounds like maybe `wrapt` will make it not possible to do the obvious workaround of putting `@wait_for` below the `@classmethod`. Which is a problem...

**Comment by itamarst** [comment]
Further investigation suggests #82 with `wrapt` might well do the trick, see discussion there.
