### ISSUE TITLE
Functions registered with @wait_for can trigger attribute error

### ISSUE THREAD

**Issue by sametmax** [itamarst/crochet#72]
I have this demo:

http://0bin.net/paste/xgIgxIo4NCtE8eQc#uCoxEeBHoyiNtPWg1NC313ccmhklegpL7N8Wgi7NMVI

When I run it, I get : 

```
INFO:werkzeug: * Running on http://127.0.0.1:8000/
INFO:twisted:Starting factory <autobahn.twisted.websocket.WampWebSocketClientFactory instance at 0x7f968917ab48>
INFO:twisted:Stopping factory <autobahn.twisted.websocket.WampWebSocketClientFactory instance at 0x7f968917ab48>
ERROR:__main__:Exception on / [GET]
Traceback (most recent call last):
  File "/home/sam/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sam/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sam/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sam/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sam/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 49, in index
    publish('com.example.on_visit', app._visits, msg = "hello from flask")
  File "/home/sam/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/crochet/_eventloop.py", line 461, in wrapper
    return eventual_result.wait(timeout)
  File "/home/sam/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/crochet/_eventloop.py", line 231, in wait
    result.raiseException()
  File "<string>", line 2, in raiseException
AttributeError: 'NoneType' object has no attribute 'publish'
```

But publish is a function attached to nothing but the current module object, so I don't understand this error.

To run the code :
```
pip install crossbar, flask, crochet
crossbar init
crossbar run
```
Then run in another terminal : 
```
python server.py
```

**Comment by sametmax** [comment]
Ah, this has been fixed : 

https://github.com/tavendo/AutobahnPython/commit/0a48b6452e26286c9d60f4326cb564276db9ba2e
